Write-Host "This is Third commit with web hook"
Write-Host "It is working "
Write-Host "yes it is working "
Write-Host " it is working when i did changes in git branch"
Write-Host " checking once terminal closed"
Write-Host "while terminal close it won't work once after generating new public ip only it will work"
Write-Host "In compeny system also trying"
